
services:

  security:
    container_name: security
    ports:
      - 8000:8000
    
    build:
      context: ./Security
      dockerfile: Dockerfile

    depends_on:
      - mq
      - cache


  mq:
    container_name: rabbitMQ
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672
    
  
  cache:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    
