name: Deploy to Azure

on:
    push:
        branches: [main]
    workflow_dispatch:

env:
    AZURE_WEBAPP_NAME: my-fastapi-app
    AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Build and push images to ACR
              run: |
                  docker compose build
                  docker compose push

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  images: |
                      security=<acr-name>.azurecr.io/security:${{ github.sha }}
                      notification=<acr-name>.azurecr.io/notification:${{ github.sha }}
                      record=<acr-name>.azurecr.io/record:${{ github.sha }}
                      cache=<acr-name>.azurecr.io/cache:${{ github.sha }}

            - name: Set Web App settings
              uses: Azure/appservice-settings@v1
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  app-settings-json: |
                      [
                        {
                          "name": "DB_URI",
                          "value": "${{ secrets.DB_URI }}"
                        },
                        {
                          "name": "TWILIO_ACCOUNT_SID",
                          "value": "${{ secrets.TWILIO_ACCOUNT_SID }}"  
                        },
                        {
                          "name": "TWILIO_AUTH_TOKEN",
                          "value": "${{ secrets.TWILIO_AUTH_TOKEN }}"
                        },
                        {
                          "name": "TWILIO_PHONE_NUMBER",
                          "value": "${{ secrets.TWILIO_PHONE_NUMBER }}"
                        },
                        {
                          "name": "MAILJET_API_KEY",
                          "value": "${{ secrets.MAILJET_API_KEY }}"
                        },
                        {
                          "name": "MAILJET_API_SECRET",
                          "value": "${{ secrets.MAILJET_API_SECRET }}"
                        },
                        {
                          "name": "MAILJET_FROM_EMAIL",
                          "value": "${{ secrets.MAILJET_FROM_EMAIL }}"
                        }
                      ]

            - name: Restart Web App
              run: az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }}
